version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=development
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=dev-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432